# Generated by Django 5.0.4 on 2024-04-24 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_category_alter_todo_id_todo_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[(1, "HEALTH"), (2, "BILLS"), (3, "WORKOUT")],
                default=None,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="todo.category",
            ),
        ),
    ]
